### PR TITLE
Create evaluations page

### LINKED ISSUE #1: [Frontend] Create a dashboard/table to keep track of applicant evaluation scores
For each student to be evaluated: Create a table, and allow reviewers to enter in their names/ids (1, 2, ...) and evaluation scores on a specified scale (1-5) for each dimension (Skills, Experience, Communication, Organization, ...).

Estimated effort/time: 3 hours for the code exploration + implementation; 2 more hours for debugging + testing

Test plan: Since this is a frontend feature, we will test by pulling the changes onto our local machines, running the code, and record the results when interacting with the feature.

Depends on #2

### LINKED ISSUE #2: [Frontend] Add a new "Evaluations" page to Teedy's top index bar
Add a new page to the website called "Evaluations" (other name suggestions are welcome). All the other frontend features will be built on this page.

Estimated effort/time: 3 hours to implement and test

Testing plan: Since this is a frontend change, we will pull the changes onto our local computers and run the code. If we can click into the new "Evaluations" page, that is enough to confirm that this feature works.

### PR DESCRIPTION
**Pull request by gracexin2003**
[Frontend] (Grace) Created a new "Evaluations" page in Teedy to keep track of the evaluations that reviewers give student applicants. Currently, the page allows a reviewer to enter in their name, along with their scores for the student's skill (1-5), experience (1-5), and whether or not to hire said student (yes/no).

[Middleware/Backend] (Laura) Created a new database table to store the evaluations, plus Java classes representing the reviewers. The backend also calculates the averages of each student's skill and experience, based on the accumulated scores of multiple reviewers.

Resolves #1, #3

### CODE REVIEW

**Review by gracexin2003 — COMMENTED** [review]
@lywu-andrew I was testing the changes by running `mvn jetty:run`. When I entered in values for each of the categories and  and found a few errors output to terminal such as:

`Column "U.USE_DELETEDATE_D" not found; SQL statement:
select u.REV_ID_C as c0, u.REV_NAME_C as c1, u.REV_SKILLS_N as c2, u.REV_EXPERIENCE_N as c3, u.REV_HIRE_N as c4 from T_REV u  where u.USE_DELETEDATE_D is null order by c0 asc [42122-199]`

These errors were due to typos in `ReviewerDao.java`, such as not changing `USE_DELETEDATE_D` to `REV_DELETEDATE_D`. I've fixed the code, and now pressing the submit button doesn't output any errors to terminal. Just in case, could someone else test and check that nothing is wrong as well?

**Comment by lywu-andrew** [comment]
LGTM! Thanks for catching my typos; I made some changes to the database and didn't change all instances of the column names throughout my code.

When I run the code and submit a reviewer's scores, I don't see any errors to terminal either. Should be good to go!

**Comment by lywu-andrew** [comment]
The changes in backend for the hire type are also good, thank you for the catch! This PR LGTM

**Comment by megkrish7** [comment]
LGTM! Everything runs without error and the updated evaluations page works.

**Pull request merged**
