### PR TITLE
Integrate evaluations full stack

### LINKED ISSUE #6: [Frontend] Display average evaluation scores of each student in their table
For each student to be evaluated, pull their averaged scores for each dimension from the backend, and display them in the last row of the table.

Estimated effort/time: 3 hours for the code exploration + implementation; 2 more hours for debugging + testing

Test plan: Since this is a frontend feature, we will test by pulling the changes onto our local machines, running the code, and record the results when interacting with the feature.

Depends on #3

### PR DESCRIPTION
**Pull request by gracexin2003**
Create frontend (javascript) functions to get the list of reviewer evaluations from the database, add a new reviewer evaluation to the database, and retrieve the average evaluations of each criterion from the backend.

@megkrish7 created the table outline; I connected the middleware/backend values and filled it out.

Depends on #7

### CODE REVIEW

**Comment by gracexin2003** [comment]
Note: this PR still needs more work and testing. It should be merged after #7 and the changes on the create-evaluations-table branch.

**Comment by gracexin2003** [comment]
Everything should be good now! Please let me know if you guys find any issues :)

**Comment by megkrish7** [comment]
LGTM!

**Comment by lywu-andrew** [comment]
Nice job with the frontend middleware integration! LGTM

**Pull request merged**
